name: agcplus
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1  # ✅ Compatible with CUDA 12.9 drivers
  - cudatoolkit
  - pip
  - pip:
      # --- Experiment config ---
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - tqdm==4.66.4
      - rich==13.8.0

      # --- Experiment tracking ---
      - mlflow==2.14.1
      - optuna==3.6.1
      - hydra-optuna-sweeper==1.1.2

      # --- Data & reproducibility ---
      - dvc==3.49.0
      - dvc[gdrive]==3.49.0

      # --- Visualization ---
      - matplotlib==3.9.2
      - seaborn==0.13.2
      - pandas==2.2.3
      - numpy==1.26.4
      - scipy==1.13.1

      # --- Utilities ---
      - pyyaml==6.0.2
      - psutil==6.0.0
      - termcolor==2.4.0
      - colorama==0.4.6

      # --- Dev & testing ---
      - jupyterlab==4.2.4
      - pytest==8.3.3
      - black==24.8.0
      - isort==5.13.2

      # --- Local package ---
      - -e .
